### ISSUE TITLE
Context doesn't hide when item chosen

### ISSUE THREAD

**Issue by etusa** [avxto/nuContextMenu#3]
Context closes if user clicks outside the box.

Broken: Context doesn't close (hide) after user selects context menu item.

**Comment by avxto** [comment]
Okay, I am going to add an option "hideAfterClick" (boolean) that will close the menu when the user selects something.

**Comment by etusa** [comment]
Thanks!  Great job on this context menu, by the way.

**Comment by avxto** [comment]
Thank you for your feedback and contribution. It should work now.
