### ISSUE TITLE
Binding to dynamically created elements

### ISSUE THREAD

**Issue by ghost** [avxto/nuContextMenu#5]
It is not attaching to dynamically created elements.

**Comment by avxto** [comment]
Hello, can you please create a JS-Fiddle illustrating the problem? Thank you.

**Comment by CGRemakes** [comment]
I am wondering the same thing.  How do we attach the context menu to items that are dynamically generated?  Here's a fiddle with a dynamically added "item-5":

http://jsfiddle.net/CGRemakes/y1ed8j1o/
