### ISSUE TITLE
Switch to regular context menu ?

### ISSUE THREAD

**Issue by balibou** [avxto/nuContextMenu#8]
Hello ! First of all thank you for your package ! It's a very nice one ! 
I'm killing myself to find a way to switch between a custom context menu using your package and the standard right click menu ... Is there a simple way to do it ? Thanks :)

**Comment by avxto** [comment]
Hello, if you want to destroy the context menu (go back to the standard menu), then just use the "destroy" method.

Example : 

``` javascript
var contextMenu = $('#node')
  .nuContextMenu({
    // Options
  });

// Then destroy the menu, reverting to the standard menu
contextMenu.nuContextMenu('destroy');
```

Thank you for using the package !

**Comment by balibou** [comment]
Mmm this is so weird because I've already tried this in your demo.html and nothing happens :(

**Comment by avxto** [comment]
Okay, I figured out the problem. It should be working now.

**Comment by balibou** [comment]
Thanks ;)
Very good job, very reactive ! I tried to fix myself but was lost ...

**Comment by avxto** [comment]
Thank you.

The problem was that when I added support for dynamically created elements, I forgot to change the destroy method. Lol

**Comment by balibou** [comment]
ahah :+1:
